### PR TITLE
Crowd-Kit Learning

### PR DESCRIPTION
**Pull request by pilot7747**
This is just an example of what this subpackage will contain.

We need to configure `setup.cfg` and add new tests. Here I suggest to discuss the concept.

### CODE REVIEW

**Comment by pilot7747** [comment]
Received a concept approve by @dustalov. Now start to adding tests and trying to configure it as a subpackage with extra requirements. Also waiting for approve by @zdchu to use a code derived from the original CoNAL implementation

**Comment by pilot7747** [comment]
@dustalov The PR is ready for a review

**Comment by dustalov** [comment]
- Please add `py.typed` to every new source directory, excluding tests: https://github.com/Toloka/crowd-kit/blob/main/crowdkit/py.typed
- Kindly move the summarization aggregation tests to the learning module tests
- We have to do it in a separate PR, but have you tried installing Crowd-Kit without the learning module to a bare venv? Has it worked?
- If you initialize parameters randomly, is it possible to choose the seed value and then canonize the tests?

**Comment by pilot7747** [comment]
> * Kindly move the summarization aggregation tests to the learning module tests

These tests have never existed. One of the reasons it is difficult to implement them is the fact they are extremely heavy. You need to download a 3 GB model from HuggingFace and do this on every commit.

> * If you initialize parameters randomly, is it possible to choose the seed value and then canonize the tests?
Yes, but I'm not sure this will be consistent across platforms and PyTorch versions.

**Comment by dustalov** [comment]
Good. We're almost there. Please fix the newlines and we're good to go.

**Comment by pilot7747** [comment]
> Please fix the newlines and we're good to go.

What newlines?

**Comment by pilot7747** [comment]
> This one: https://github.com/Toloka/crowd-kit/pull/47/files/b4d07cc2eb30db31ca6234d8bec4f7530afe3dec#diff-f1e0b25eeb099b940ecba4b0d893c38ef7ad7d122ab962a58118fef33936d4f5

Done. I specifically checked for other py.typed files and looked if they have a trailing newline but I didn't realize that GitHub doesn't show trailing newlines.

**Review by dustalov — COMMENTED** [review]
Good.

**Review by dustalov — APPROVED** [review]

**Comment by pilot7747** [comment]
Btw, yes, I've checked, the package installs without `learning` extra

**Pull request merged**
