### PR TITLE
Fix the documentation generation issues

### PR DESCRIPTION
**Pull request by dustalov**
Stick to YAML files hosted in https://github.com/Toloka/docs and use the proper includes.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation and examples improvement (changes affected documentation and/or examples)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by dustalov** [comment]
@varfolomeii @DrhF @alexdrydew @alexandervnuchkov  please have a look at this. It passes all the tests, but I am not sure if I understand what I am doing.

Tests are failing on 3.10 due to https://github.com/python/mypy/issues/13627.

**Comment by alexandervnuchkov** [comment]
We can, but if you change the docs structure (add new pages, remove some existing ones), it should be changed in these files as well, otherwise the new pages will not be included into the documentation and the old ones will throw exceptions if deleted

**Comment by alexandervnuchkov** [comment]
If the structure is the same in this commit as it was in the current version of docs, then it's okay not to add these files at all, I suppose

**Comment by dustalov** [comment]
I see no problem in keeping these files in `docs` intact. When we add something new, we will update the YAML metadata there. Should it work for us?

**Comment by alexandervnuchkov** [comment]
Yes, sure

**Review by DrhF — APPROVED** [review]

**Comment by dustalov** [comment]
@alexandervnuchkov I'll create another release candidate right now to see if it works.

**Comment by dustalov** [comment]
It seems to be working: https://github.com/Toloka/docs/pull/103.

**Pull request merged**
