### PR TITLE
Glad labels prior bug

### PR DESCRIPTION
**Pull request by alexdremov**
I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en.

В случае указания приора на лейблах, падает фит так как `self.prior_labels_` не определен

## Checklist

- [ v] I have read the **CONTRIBUTING** document
- [v ] I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en
- [x ] My change requires a change to the documentation
- [x ] I have updated the documentation accordingly
- [x ] I have added tests to cover my changes
- [v ] All new and existing tests passed

### CODE REVIEW

**Comment by dustalov** [comment]
Thank you! We're happy to merge this, but please fix the typing so that the tests pass.

**Comment by alexdremov** [comment]
> Thank you! We're happy to merge this, but please fix the typing so that the tests pass.

@dustalov I don't understand reasons for tests failure. Could you check them please?

**Comment by pilot7747** [comment]
@alexdremov Please rebase your branch, we've fixed those test in main

**Comment by pilot7747** [comment]
Probably we can just merge this PR, I don't think the tests will fail. If it happens, blame me, I'm going to fix them myself.

**Review by pilot7747 — APPROVED** [review]

**Pull request merged**
