### PR TITLE
Install mypy in tests

### PR DESCRIPTION
**Pull request by pilot7747**
Now test fail because of `mypy not found`, try to install it directly

## Checklist

- [x] I have read the **CONTRIBUTING** document
- [x] I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by dustalov** [comment]
mypy is already required as a development dependency: https://github.com/Toloka/crowd-kit/blob/ff36f90a3ccf46f589850aae67d20df1ca4e9518/setup.cfg#L56

Please investigate if it is installed properly via pipenv.

**Comment by pilot7747** [comment]
In parallel PR tests say that `mypy` isn't installed. Here the tests also fail but for some other reason. Seems like a change in mypy, need to investigate

**Comment by dustalov** [comment]
Yep, something definitely happened. Everything worked until recently.

https://github.com/Toloka/crowd-kit/actions/runs/5520833629/job/14950582157

**Comment by dustalov** [comment]
Fixed in the upstream.

**Pull request closed without merging**
